service: apfest2022-hackathon-go

frameworkVersion: ">=3.0"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2

functions:
  databases:
    handler: bin/databases
    events:
      - httpApi:
          path: /databases
          method: get

package:
  patterns:
    - '!./**'
    - ./bin/**
